/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2022-02-20 12:14:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Tomcat</title>\n");
      out.write("\t\t<meta charset=\"UTF-8\"></meta>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"row jumbotron\">\n");
      out.write("\t\t\t\t<div class=\"col-md-1\">\n");
      out.write("\t\t\t\t\t\t<img src=\"icon.png\" alt=\"icon.png\" style=\"height:128;\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-11\">\n");
      out.write("\t\t\t\t\t<h1 class=\"display-3\">Tomcat for Visual Studio Code</h1>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\n");
      out.write("\t\t");
 
			String file = application.getRealPath("/");
			File f = new File(file);
			String webappsPath = f.getParent();
			File webapps = new File(webappsPath);
		
      out.write("\n");
      out.write("\t\t\t<div class=\"row\"><h2>War Packages Deployed on this Tomcat Server:</h2></div>\n");
      out.write("\t\t\t<div class=\"row\" style=\"font-size: 22px;\">\n");
      out.write("\t\t\t\t<ul class=\"list-group\">\n");
      out.write("\t\t\t\t");

					String [] fileNames = webapps.list();
					File [] fileObjects= webapps.listFiles();
					int packagesCount = 0;
					for (int i = 0; i < fileObjects.length; i++) {
						if(fileObjects[i].isDirectory() && !("ROOT").equalsIgnoreCase(fileNames[i])){
							String fname = file+fileNames[i];
							++packagesCount;
				
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\"><span class=\"glyphicon glyphicon-folder-close\"></span><a href=\"");
      out.print( fileNames[i] );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print( fileNames[i] );
      out.write("</a></li>\n");
      out.write("\t\t\t\t");

						}
					}
					if (packagesCount == 0) {
				
      out.write("\n");
      out.write("\t\t\t\t\t<h4>No war package</h4>\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
